const { app } = require('@azure/functions');
// generated by scripts/update-stations.js - already filtered to NOAA reference
// stations and trimmed to the fields used here, so no work is needed at load
const stations = require('../data/stations.js');

// Past this, the nearest station is not describing the water where the user is.
// Measured across 47 US cities, everywhere genuinely tidal - including inland
// tidal rivers like Albany and Sacramento - sits within 57 km, while the nearest
// non-tidal place is 308 km out, so anything in that band behaves identically.
const MAX_STATION_DISTANCE_KM = 100;

// this endpoint should be hit by GetCoords
const handler = async (request, context) => {
    context.log(`Processing http function request for url "${request.url}"`);
    // get locaton from query parameter
    const queryLocation = request.query.get('location');

    const apiKey = process.env.GEO_API_KEY;

    // if query location is a falsey value
    if (!queryLocation) {
        context.log(`Query parameter 'location' is null. Received: ${queryLocation}`);
        return {
            status: 400,
            headers: {
                'Content-Type' : 'application/json'
            },
            body: JSON.stringify({
                error: `Query parameter 'location' is null.`
            })
        };
    }

    let geocodeData;

    // fetch the geocode api
    try {
        const geocodeApiUrl = `https://geocode.maps.co/search?q=${encodeURIComponent(queryLocation)}&countrycodes=us`;
        const geocodeRes =  await fetch(geocodeApiUrl, {
            headers: {
                'Authorization': `Bearer ${apiKey}` // add API key in the headers for security
            }
        });

        // throw an error if there is a bad response
        if (!geocodeRes.ok) {
            throw new Error(`API responded with status: ${geocodeRes.status}`);
        }

        geocodeData = await geocodeRes.json();
        geocodeData = geocodeData[0];

        // if data is null return 404
        if (!geocodeData) {
            return {
                status: 404,
                headers: {
                    'Content-Type' : 'application/json'
                },
                body: JSON.stringify({
                    error: 'No results found'
                })
            };
        }
    } catch (err) {
        context.error(`Geocode fetch failed: ${err.message}`);
        return {
            status: 502,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                error: "Failed to fetch from geocode.maps.co"
            })
        };
    }

    const { station, distance } = getClosestStation({lat: geocodeData.lat, lng: geocodeData.lon}, stations);
    const distanceKm = Math.round(distance * 10) / 10;

    // no tides here - say so rather than charting water hundreds of km away
    if (distance > MAX_STATION_DISTANCE_KM) {
        context.log(`No station within ${MAX_STATION_DISTANCE_KM} km of ${queryLocation}; nearest is ${station.name} at ${distanceKm} km`);
        return {
            status: 404,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                error: `No tide station near ${geocodeData.name || queryLocation}. The nearest one is ${station.name}, ${distanceKm} km away.`,
                nearestStation: { name: station.name, distanceKm }
            })
        };
    }

    // fetch the NOAA tides api
    try {
        // the 6-minute series carries the curve and the current reading; the hilo
        // product carries NOAA's own high/low times, which are computed from
        // harmonic constituents rather than read off a sampled series
        const [predictions, extremes] = await Promise.all([
            fetchPredictions(station.id),
            fetchPredictions(station.id, { interval: 'hilo' })
        ]);

        // create response object
        const responseJson = {
            name: geocodeData.name,
            displayName: geocodeData.display_name,
            address: geocodeData.address,
            predictions,
            extremes,
            station: { name: station.name, distanceKm }
        };

        return {
            status: 200,
            headers: { 'Content-Type': 'application/json'},
            body: JSON.stringify(responseJson)
        }
    } catch (err) {
        context.error(`NOAA tides fetch failed: ${err.message}`);
        return {
            status: 502,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                error: "Failed to fetch from tides.noaa.gov"
            })
        };
    }
};

app.http('GetTides', {
    methods: ['GET'],
    handler
});

function buildPredictionsUrl(stationId, { interval } = {}) {
    const params = new URLSearchParams({
        station: stationId,
        product: 'predictions',
        date: 'today',
        datum: 'MLLW',
        units: 'english', // feet - the UI labels heights in feet and this is a US-only app
        time_zone: 'lst_ldt',
        format: 'json'
    });

    if (interval) {
        params.set('interval', interval);
    }

    return `https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?${params}`;
}

async function fetchPredictions(stationId, options) {
    const res = await fetch(buildPredictionsUrl(stationId, options));

    if (!res.ok) {
        throw new Error(`API responded with status: ${res.status}`);
    }

    const data = await res.json();
    return data.predictions;
}

// finds the closest station to the input coordinates, and how far away it is -
// the distance decides whether the location has usable tide data at all
function getClosestStation(coords, stationList) {
    const EARTH_RADIUS_KM = 6371;

    // great-circle distance in km. a degree of longitude covers less ground the
    // further you get from the equator, so comparing raw lat/lng degrees picks
    // the wrong station at northern latitudes. Number() because the geocode API
    // hands back coordinates as strings.
    function calcDistance(lat1, lon1, lat2, lon2) {
        const toRadians = degrees => Number(degrees) * Math.PI / 180;

        const lat1Rad = toRadians(lat1);
        const lat2Rad = toRadians(lat2);
        const deltaLat = lat2Rad - lat1Rad;
        const deltaLon = toRadians(lon2) - toRadians(lon1);

        const a = Math.sin(deltaLat / 2)**2
            + Math.cos(lat1Rad) * Math.cos(lat2Rad) * Math.sin(deltaLon / 2)**2;

        return EARTH_RADIUS_KM * 2 * Math.asin(Math.sqrt(a));
    }

    // carry the running best distance rather than recomputing it for the incumbent
    // on every step - this runs across the whole tidal station list per request
    const closest = stationList.reduce((best, station) => {
        const distance = calcDistance(coords.lat, coords.lng, station.lat, station.lng);

        return distance < best.distance ? { station, distance } : best;
    }, { station: stationList[0], distance: Infinity });

    return closest;
}

module.exports = { handler, getClosestStation, buildPredictionsUrl, MAX_STATION_DISTANCE_KM };