const { app } = require('@azure/functions');
// generated by scripts/update-stations.js - already filtered to NOAA reference
// stations and trimmed to the fields used here, so no work is needed at load
const stations = require('../data/stations.js');

// this endpoint should be hit by GetCoords
const handler = async (request, context) => {
    context.log(`Processing http function request for url "${request.url}"`);
    // get locaton from query parameter
    const queryLocation = request.query.get('location');

    const apiKey = process.env.GEO_API_KEY;

    // if query location is a falsey value
    if (!queryLocation) {
        context.log(`Query parameter 'location' is null. Received: ${queryLocation}`);
        return {
            status: 400,
            headers: {
                'Content-Type' : 'application/json'
            },
            body: JSON.stringify({
                error: `Query parameter 'location' is null.`
            })
        };
    }

    let geocodeData;

    // fetch the geocode api
    try {
        const geocodeApiUrl = `https://geocode.maps.co/search?q=${encodeURIComponent(queryLocation)}&countrycodes=us`;
        const geocodeRes =  await fetch(geocodeApiUrl, {
            headers: {
                'Authorization': `Bearer ${apiKey}` // add API key in the headers for security
            }
        });

        // throw an error if there is a bad response
        if (!geocodeRes.ok) {
            throw new Error(`API responded with status: ${geocodeRes.status}`);
        }

        geocodeData = await geocodeRes.json();
        geocodeData = geocodeData[0];

        // if data is null return 404
        if (!geocodeData) {
            return {
                status: 404,
                headers: {
                    'Content-Type' : 'application/json'
                },
                body: JSON.stringify({
                    error: 'No results found'
                })
            };
        }
    } catch (err) {
        context.error(`Geocode fetch failed: ${err.message}`);
        return {
            status: 502,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                error: "Failed to fetch from geocode.maps.co"
            })
        };
    }

    // fetch the NOAA tides api
    try {
        const closestStationId = getClosestStation({lat: geocodeData.lat, lng: geocodeData.lon}, stations).id;

        const tidesApiUrl = `https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?station=${closestStationId}&product=predictions&date=today&datum=MLLW&units=metric&time_zone=lst_ldt&format=json`;
        const tidesRes = await fetch(tidesApiUrl);

        if (!tidesRes.ok) {
            throw new Error(`API responded with status: ${tidesRes.status}`);
        }

        const tidesData = await tidesRes.json();

        // create response object
        const responseJson = {
            name: geocodeData.name,
            displayName: geocodeData.display_name,
            address: geocodeData.address,
            predictions: tidesData.predictions,
        };

        return {
            status: 200,
            headers: { 'Content-Type': 'application/json'},
            body: JSON.stringify(responseJson)
        }
    } catch (err) {
        context.error(`NOAA tides fetch failed: ${err.message}`);
        return {
            status: 502,
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                error: "Failed to fetch from tides.noaa.gov"
            })
        };
    }
};

app.http('GetTides', {
    methods: ['GET'],
    handler
});

// function to calculate the closest station to the input coordinates
function getClosestStation(coords, stationList) {
    const EARTH_RADIUS_KM = 6371;

    // great-circle distance in km. a degree of longitude covers less ground the
    // further you get from the equator, so comparing raw lat/lng degrees picks
    // the wrong station at northern latitudes. Number() because the geocode API
    // hands back coordinates as strings.
    function calcDistance(lat1, lon1, lat2, lon2) {
        const toRadians = degrees => Number(degrees) * Math.PI / 180;

        const lat1Rad = toRadians(lat1);
        const lat2Rad = toRadians(lat2);
        const deltaLat = lat2Rad - lat1Rad;
        const deltaLon = toRadians(lon2) - toRadians(lon1);

        const a = Math.sin(deltaLat / 2)**2
            + Math.cos(lat1Rad) * Math.cos(lat2Rad) * Math.sin(deltaLon / 2)**2;

        return EARTH_RADIUS_KM * 2 * Math.asin(Math.sqrt(a));
    }

    // carry the running best distance rather than recomputing it for the incumbent
    // on every step - this runs across the whole tidal station list per request
    const closest = stationList.reduce((best, station) => {
        const distance = calcDistance(coords.lat, coords.lng, station.lat, station.lng);

        return distance < best.distance ? { station, distance } : best;
    }, { station: stationList[0], distance: Infinity });

    return closest.station;
}

module.exports = { handler, getClosestStation };